name: new_explorer_challenge
description: New Explorer Challenge

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Dependencies Firebase
  firebase_auth: ^1.0.1
  firebase_auth_platform_interface: ^4.0.0
  firebase_auth_web: ^1.0.3
  firebase_core: ^1.0.2
  firebase_core_web: ^1.0.2
  cloud_firestore: ^1.0.2
  cloud_firestore_platform_interface: ^4.0.0
  cloud_firestore_web: ^1.0.2
  firebase_storage: ^8.0.0
  firebase_storage_platform_interface: ^2.0.0
  firebase_storage_web: ^1.0.2


  #Other Dependencies
  image_picker: ^0.7.3
  image_picker_platform_interface: ^2.0.1
  image_picker_for_web: ^2.0.0
  curved_navigation_bar: ^0.3.7
  fluttertoast: ^8.0.3
  google_fonts: ^2.0.0
  cached_network_image: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mountain.png
    - assets/mountains.png
    - assets/ostrich.png
    - assets/red-poppy.png
    - assets/rice.png
    - assets/adventure.png
    - assets/joyride.png
    - assets/logo_NEC_.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
